apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billing-security-policy
spec:
  podSelector:
    matchLabels:
      app: billing
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: gateway
